"use client";
import {useState} from "react";
const models=["Automático","GPT","Claude","Gemini","DeepSeek"];
const prompts=[["</>","Crie uma função em Python","Programação"],["▤","Resuma este artigo","Escrita"],["⌁","Analise este documento","Análise"],["⌕","Pesquise sobre um tema","Pesquisa"],["◉","Me dê ideias de negócio","Geral"],["▣","Explique de forma simples","Geral"]];
export default function Home(){const [model,setModel]=useState("Automático");const [text,setText]=useState("");const [sent,setSent]=useState(false);function submit(){if(!text.trim())return;setSent(true)}return <main className="app">
<aside className="side"><div className="logo"><b>AI</b> HUB</div><nav><button className="active">⌂ <span>Chat</span></button><button>□ <span>Projetos</span></button><button>♧ <span>Memória</span></button><button>▤ <span>Arquivos</span></button><button>⚖ <span>Comparar IAs</span></button><button>▣ <span>Agentes</span></button><button>◉ <span>Automatizações</span></button><button>▥ <span>Estatísticas</span></button><button>⚙ <span>Configurações</span></button></nav><div className="plan"><b>⚡ Plano Atual</b><strong>Free</strong><small>Você está usando o plano gratuito.</small><a>Ver planos →</a></div></aside>
<section className="workspace"><header><div className="topSearch">⌕ <span>Buscar conversas, projetos, arquivos...</span><kbd>Ctrl K</kbd></div><div className="topModels"><span className="auto">● Automático⌄</span><span>◉ GPT</span><span>✳ Claude</span><span>✦ Gemini</span><span>◉ DeepSeek</span></div><div className="user">⌕　♧　<b>C</b></div></header>
<div className="center"><h1>Bem-vindo ao <mark>AI HUB</mark></h1><p>Um único lugar para conversar com as melhores IAs, com memória, projetos e automações.</p><small>O Router escolhe automaticamente o modelo ideal ou você pode selecionar manualmente.</small>
<div className="modelRow">{models.map(m=><button key={m} className={model===m?"selected":""} onClick={()=>setModel(m)}>{m==="Automático"?"🤖":m==="GPT"?"◉":m==="Claude"?"✳":m==="Gemini"?"✦":"◉"} {m}</button>)}</div>
{sent&&<div className="conversationPreview"><div className="userBubble">{text}</div><div className="aiBubble"><b>AI HUB</b><span>Pronto para enviar esta pergunta pelo Router. A conexão com os modelos será ativada na próxima etapa.</span></div></div>}<div className="promptbox"><textarea value={text} onChange={e=>setText(e.target.value)} placeholder="Pergunte qualquer coisa..." /><div className="tools"><span>📎</span><div className="quicktools"><span>◉ Pesquisar na web</span><span>♧ Usar memória</span><span>&lt;/&gt; Código</span><span>▥ Analisar dados</span><span>▧ Gerar imagem</span></div><button onClick={submit} disabled={!text.trim()}>➤</button></div></div>
<label>Exemplos de como começar:</label><div className="examples">{prompts.map(([i,t,k])=><button key={t}><i>{i}</i><span><b>{t}</b><small>{k}</small></span></button>)}</div></div></section>
<aside className="right"><div className="panel modelPanel"><h3>Modelo selecionado</h3><div className="selectedModel">◎ Automático　⌄</div><small>O sistema escolhe a melhor IA para cada tarefa.</small><div className="modelList"><span>◉ GPT <i>○</i></span><span>✳ Claude <i>○</i></span><span>✦ Gemini <i>○</i></span><span>◉ DeepSeek <i>○</i></span></div></div><div className="panel"><h3>♧ Memória <a>Ver tudo →</a></h3><div className="memory"><b>● Memória ativa</b><small>Suas conversas, preferências e projetos ficam salvos para você.</small></div></div><div className="panel"><h3>□ Projetos <a>Ver tudo →</a></h3>{["Pessoal","AUTO PARTS","Estudos"].map((x,i)=><div className="project" key={x}><i className={"dot d"+i}></i><span><b>{x}</b><small>{12-i*4} conversas</small></span><em>›</em></div>)}<button className="newProject">＋ Novo projeto</button></div><div className="panel recent"><h3>◷ Últimas conversas <a>Ver tudo →</a></h3><p>◉ Como criar uma API com Node.js<small>há 2 horas</small></p><p>✦ Análise de estratégias de marketing<small>há 4 horas</small></p><p>✳ Resumo do artigo sobre IA<small>há 6 horas</small></p></div></aside></main>}