"use client";
import {useState} from "react";
const models=["Automático","GPT","Claude","Gemini","DeepSeek"];
const prompts=[["</>","Crie uma função em Python","Programação"],["▤","Resuma este artigo","Escrita"],["⌁","Analise este documento","Análise"],["⌕","Pesquise sobre um tema","Pesquisa"],["◉","Me dê ideias de negócio","Geral"],["▣","Explique de forma simples","Geral"]];
export default function Home(){const [model,setModel]=useState("Automático");const [text,setText]=useState("");return <main className="app">
<aside className="side"><div className="logo"><b>AI</b> HUB</div><nav><button className="active">⌂ <span>Chat</span></button><button>□ <span>Projetos</span></button><button>♧ <span>Memória</span></button><button>▤ <span>Arquivos</span></button><button>⚖ <span>Comparar IAs</span></button><button>▣ <span>Agentes</span></button><button>⚙ <span>Configurações</span></button></nav><div className="plan"><b>⚡ Plano Atual</b><strong>Free</strong><small>Você está usando o plano gratuito.</small><a>Ver planos →</a></div></aside>
<section className="workspace"><header><div className="tagline">Todas as IAs, um só lugar.</div><div className="topModels"><span className="auto">● Automático⌄</span><span>◉ GPT</span><span>✳ Claude</span><span>✦ Gemini</span><span>◉ DeepSeek</span></div><div className="user">⌕　♧　<b>C</b></div></header>
<div className="center"><h1>Olá, Caduu! 👋</h1><p>Pergunte qualquer coisa. O AI HUB escolhe a melhor IA para você.</p><small>Ou selecione manualmente o modelo que prefere.</small>
<div className="modelRow">{models.map(m=><button key={m} className={model===m?"selected":""} onClick={()=>setModel(m)}>{m==="Automático"?"🤖":m==="GPT"?"◉":m==="Claude"?"✳":m==="Gemini"?"✦":"◉"} {m}</button>)}</div>
<div className="promptbox"><textarea value={text} onChange={e=>setText(e.target.value)} placeholder="Pergunte qualquer coisa..." /><div className="tools"><span>⌕　▤　▧</span><button disabled={!text.trim()}>➤</button></div></div>
<label>Exemplos de como começar:</label><div className="examples">{prompts.map(([i,t,k])=><button key={t}><i>{i}</i><span><b>{t}</b><small>{k}</small></span></button>)}</div></div></section>
<aside className="right"><div className="panel"><h3>♧ Memória <a>Ver tudo →</a></h3><div className="memory"><b>● Memória ativa</b><small>Suas conversas, preferências e projetos ficam salvos para você.</small></div></div><div className="panel"><h3>□ Projetos <a>Ver tudo →</a></h3>{["Pessoal","AUTO PARTS","Estudos"].map((x,i)=><div className="project" key={x}><i className={"dot d"+i}></i><span><b>{x}</b><small>{12-i*4} conversas</small></span><em>›</em></div>)}<button className="newProject">＋ Novo projeto</button></div><div className="panel recent"><h3>◷ Últimas conversas <a>Ver tudo →</a></h3><p>◉ Como criar uma API com Node.js<small>há 2 horas</small></p><p>✦ Análise de estratégias de marketing<small>há 4 horas</small></p><p>✳ Resumo do artigo sobre IA<small>há 6 horas</small></p></div></aside></main>}